# **Table of Contents**


1. [Importing Libraries and Loading Data](#Importing-Libraries-and-Loading-Data)
2. [Data Cleaning & Preprocessing](#Data-Cleaning-&-Preprocessing)
3. [Handling Missing Values](#Handling-Missing-Values)
4. [Model Building](#Model-Building)
6. [Lazzy Regressor Results](#Lazzy-Regressor-Results)
7. [Neural Network](#Neural-Network)

# Importing Libraries and Loading Data

In [4]:
!pip install lazypredict

Requirement already satisfied: lazypredict in /usr/local/lib/python3.11/dist-packages (0.2.13)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from lazypredict) (8.1.8)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from lazypredict) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from lazypredict) (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from lazypredict) (4.67.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from lazypredict) (1.4.2)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.11/dist-packages (from lazypredict) (4.5.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.11/dist-packages (from lazypredict) (2.1.3)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from lightgbm->lazypredict) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from lightgbm->lazypredict) (1.13.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->lazypredict) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->lazypredict) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->lazypredict) (2025.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->lazypredict) (3.5.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.11/dist-packages (from xgboost->lazypredict) (2.21.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->lazypredict) (1.17.0)

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from lazypredict.Supervised import LazyRegressor
import tensorflow as tf

In [66]:
df = pd.read_csv("./intern_car_regg.csv")
df.head()

,Avtosalon,Qiymet,Valyuta,Şəhər,Marka,Model,Buraxılış ili,Ban növü,Rəng,Mühərrik,...,Yeni,Vəziyyəti,Yeniləndi,Baxışların sayı,Extra,Etrafli,Sahiblər,Hansı bazar üçün yığılıb,Yerlərin sayı,Qəzalı
0,0,13500,AZN,Bakı,Opel,Vectra,2000,Hetçbek,Göy,1.6 L/101 a.g./Benzin,...,Xeyr,"Vuruğu yoxdur, rənglənib",28.05.2023,267,"Yüngül lehimli disklər, ABS, Kondisioner, Dəri...",Salam Barter mümkündür. 1.6 sadə mator mexanik...,2,Avropa,5,NaN
1,1,23500,USD,Bakı,Toyota,Corolla,2023,Sedan,Mavi,1.8 L/178 a.g./Hibrid,...,Bəli,"Vuruğu yoxdur, rənglənməyib",28.05.2023,12410,"Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...",TOYOTA CAROLLA 2023 ALIŞ. 2 İL 80.000 KM ZƏMAN...,1,Rəsmi diler,5,NaN
2,0,33200,AZN,Bakı,Hyundai,Santa Fe,2013,Offroader / SUV,Qara,2.0 L/184 a.g./Dizel,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",28.05.2023,148,"Yüngül lehimli disklər, ABS, Lyuk, Yağış senso...",Yeni gelib bakida surlmuyb qiymet mawin yanind...,1,Avropa,7,NaN
3,0,17000,AZN,Bakı,Ford,Fusion,2015,Sedan,Göy,1.5 L/181 a.g./Benzin,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",25.05.2023,3358,"Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...",Maşın xanım tərəfindən idarə olunub,NaN,NaN,NaN,NaN
4,0,36000,USD,Bakı,Toyota,RAV4,2022,Offroader / SUV,Qara,2.0 L/173 a.g./Benzin,...,Bəli,"Vuruğu yoxdur, rənglənməyib",28.05.2023,16183,"Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...",Rəsmi dilerdən 10 il və ya 160.000 km zəmanəti...,1,NaN,5,NaN

In [7]:
df.columns =  df.columns.str.lower()
df.apply(lambda col: col.str.strip() if (col.dtype==object) else col)

df.head()

,avtosalon,qiymet,valyuta,şəhər,marka,model,buraxılış ili,ban növü,rəng,mühərrik,...,yeni,vəziyyəti,yeniləndi,baxışların sayı,extra,etrafli,sahiblər,hansı bazar üçün yığılıb,yerlərin sayı,qəzalı
0,0,13500,AZN,Bakı,Opel,Vectra,2000,Hetçbek,Göy,1.6 L/101 a.g./Benzin,...,Xeyr,"Vuruğu yoxdur, rənglənib",28.05.2023,267,"Yüngül lehimli disklər, ABS, Kondisioner, Dəri...",Salam Barter mümkündür. 1.6 sadə mator mexanik...,2,Avropa,5,NaN
1,1,23500,USD,Bakı,Toyota,Corolla,2023,Sedan,Mavi,1.8 L/178 a.g./Hibrid,...,Bəli,"Vuruğu yoxdur, rənglənməyib",28.05.2023,12410,"Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...",TOYOTA CAROLLA 2023 ALIŞ. 2 İL 80.000 KM ZƏMAN...,1,Rəsmi diler,5,NaN
2,0,33200,AZN,Bakı,Hyundai,Santa Fe,2013,Offroader / SUV,Qara,2.0 L/184 a.g./Dizel,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",28.05.2023,148,"Yüngül lehimli disklər, ABS, Lyuk, Yağış senso...",Yeni gelib bakida surlmuyb qiymet mawin yanind...,1,Avropa,7,NaN
3,0,17000,AZN,Bakı,Ford,Fusion,2015,Sedan,Göy,1.5 L/181 a.g./Benzin,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",25.05.2023,3358,"Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...",Maşın xanım tərəfindən idarə olunub,NaN,NaN,NaN,NaN
4,0,36000,USD,Bakı,Toyota,RAV4,2022,Offroader / SUV,Qara,2.0 L/173 a.g./Benzin,...,Bəli,"Vuruğu yoxdur, rənglənməyib",28.05.2023,16183,"Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...",Rəsmi dilerdən 10 il və ya 160.000 km zəmanəti...,1,NaN,5,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   avtosalon                 10000 non-null  int64
 1   qiymet                    10000 non-null  int64
 2   valyuta                   10000 non-null  object
 3   şəhər                     10000 non-null  object
 4   marka                     10000 non-null  object
 5   model                     10000 non-null  object
 6   buraxılış ili             10000 non-null  int64
 7   ban növü                  10000 non-null  object
 8   rəng                      10000 non-null  object
 9   mühərrik                  10000 non-null  object
 10  yürüş                     10000 non-null  object
 11  sürətlər qutusu           10000 non-null  object
 12  ötürücü                   10000 non-null  object
 13  yeni                      10000 non-null  object
 14  vəziyyəti                 9972 non-null   object
 15  yeniləndi                 10000 non-null  object
 16  baxışların sayı           10000 non-null  int64
 17  extra                     9236 non-null   object
 18  etrafli                   9718 non-null   object
 19  sahiblər                  6193 non-null   object
 20  hansı bazar üçün yığılıb  6702 non-null   object
 21  yerlərin sayı             6832 non-null   object
 22  qəzalı                    32 non-null     object
dtypes: int64(4), object(19)
memory usage: 1.8+ MB

In [9]:
df.describe()

       avtosalon    qiymet  buraxılış ili  baxışların sayı
count   10000.00  10000.00       10000.00         10000.00
mean        0.25  27318.52        2010.07          4328.82
std         0.44  28995.79           8.39         13383.51
min         0.00   1100.00        1938.00            41.00
25%         0.00  12700.00        2006.00           408.75
50%         0.00  21000.00        2011.00          1164.50
75%         1.00  32500.00        2015.00          3500.25
max         1.00 850000.00        2023.00        334547.00

# Data Cleaning & Preprocessing

In [10]:
df.valyuta.unique()

array(['AZN', 'USD', 'EUR'], dtype=object)

In [11]:
currency = [1, 1.7, 1.9]
converted_val = df.valyuta.replace(["AZN", "USD", "EUR"], currency)

df.drop(columns="valyuta", inplace=True)
df.qiymet = df.qiymet.mul(converted_val).astype(int)

In [12]:
df.şəhər.unique()

array(['Bakı', 'Şamaxı', 'Gəncə', 'Lənkəran', 'Sumqayıt', 'Saatlı',
       'Quba', 'Salyan', 'Ağdaş', 'Şirvan', 'Xırdalan', 'Sabirabad',
       'Mingəçevir', 'Ağcabədi', 'Bərdə', 'Oğuz', 'Tərtər', 'Astara',
       'Zaqatala', 'Xaçmaz', 'Şəki', 'İsmayıllı', 'Neftçala', 'Göyçay',
       'Şəmkir', 'Tovuz', 'Goranboy', 'Zərdab', 'İmişli', 'Xudat',
       'Balakən', 'Qax', 'Hacıqabul', 'Kürdəmir', 'Masallı', 'Naxçıvan',
       'Ucar', 'Qusar', 'Göygöl', 'Qəbələ', 'Qazax', 'Yevlax', 'Ağdam',
       'Cəlilabad', 'Şabran', 'Göytəpə', 'Siyəzən', 'Biləsuvar',
       'Dəliməmmədli', 'Naftalan', 'Beyləqan', 'Samux', 'Lerik',
       'Gədəbəy', 'Füzuli', 'Ağstafa', 'Cəbrayıl', 'Qobustan', 'Xızı',
       'Ağsu', 'Yardımlı'], dtype=object)

In [13]:
encoder = LabelEncoder()
df.şəhər = encoder.fit_transform(df.şəhər)

In [14]:
df.marka.unique()

array(['Opel', 'Toyota', 'Hyundai', 'Ford', 'Mercedes', 'Chevrolet',
       'BMW', 'Khazar', 'LADA (VAZ)', 'Kia', 'Volkswagen', 'Haval',
       'Honda', 'Nissan', 'Ravon', 'Land Rover', 'Lexus', 'Audi',
       'Bestune', 'Infiniti', 'Renault', 'Fiat', 'Mercedes-Maybach',
       'GAZ', 'MAN', 'Isuzu', 'Skoda', 'Daewoo', 'Great Wall', 'Jeep',
       'KamAz', 'JAC', 'Hongqi', 'IJ', 'MAZ', 'Chery', 'Peugeot',
       'Mitsubishi', 'Mazda', 'Bentley', 'Subaru', 'Tofas', 'Iran Khodro',
       'DAF', 'Changan', 'Dodge', 'Ssang Yong', 'Mini', 'Volvo',
       'Polaris', 'Scania', 'Suzuki', 'Porsche', 'Lamborghini', 'Shacman',
       'Baic', 'Tufan', 'Tesla', 'Lincoln', 'FAW', 'Moskvich', 'Zontes',
       'McLaren', 'ZIL', 'Yamaha', 'UAZ', 'CFMOTO', 'Geely', 'GMC',
       'Bajaj', 'Alfa Romeo', 'Wuling', 'Jaguar', 'Iveco', 'Dacia',
       'Zeekr', 'GAC', 'Ducati', 'ZAZ', 'RKS', 'SEAT', 'Hummer', 'BYD',
       'Cadillac', 'Mercury', 'Saipa', 'KAIYI', 'Maserati', 'MG',
       'Chrysler', 'HOWO', 'Lifan', 'Muravey', 'SamAuto', 'Skywell',
       'DFSK', 'DongFeng', 'Abarth', 'Jianshe', 'Polestar', 'Foton',
       'Avatr', 'Genesis', 'Haima', 'MV Agusta', 'Smart', 'Moto Guzzi',
       'Wanfeng', 'Minsk', 'Buell', 'Harley-Davidson'], dtype=object)

In [15]:
encoder = LabelEncoder()
df.marka = encoder.fit_transform(df.marka)

In [16]:
df.model.unique()

array(['Vectra', 'Corolla', 'Santa Fe', 'Fusion', 'RAV4', 'E 200',
       'Equinox', 'Astra', '520', 'Cruze', 'C 200', 'LX', '2106', 'Rio',
       '2107', 'Passat CC', '190', 'H6', 'Highlander', 'Prius', 'Civic',
       'SD', 'i30', 'Sorento', 'Maxima', 'Note', 'ix35', 'Land Cruiser',
       'S 500', 'Nexia R3', 'RR Evoque', 'Sonata', '430', 'Niva',
       'Elantra', '2115', 'e:NS1', 'GLE 53 AMG', 'GLK 350', 'C 250',
       '528', 'E 220', 'CT 200h', 'Nexia', 'E 240', 'Malibu', '21099',
       'Ceed', 'Optima', 'Captiva', '325', 'HD-45', 'E 350', '745',
       'RR Sport', '21013', 'Range Rover', 'Cerato', 'A6', 'Prado',
       'X-Trail', 'T99', 'Transit', 'FX35', 'QX70', 'Grand Scenic',
       '500L', 'GLE 400 Coupe', 'Magentis', '2112', 'RX 350', 'Grandeur',
       'C 180', 'S 580 4MATIC', '33027', '523', 'Discovery', 'TGA 18.400',
       'Defender', 'Camry', 'Tiida', 'Premium 420', 'NMR 85 H', '525',
       'E 270', 'Vito', 'Priora', 'C 230', 'GL 500', 'Trax', 'Megane',
       'Kamiq', 'Corsa', 'E 300 e', 'Accent', 'Aveo', 'IS 200', '21011',
       'Explorer', 'Voleex C30', 'Grand Cherokee', 'i4', '5410', 'Tayron',
       'March', 'C 220', 'Tucson', 'Sportage', '200 D', 'G 63 AMG',
       'E 280', 'Vito 115', '530', 'ID.4', 'J7', 'X5', 'HS5', 'X7',
       'Vito 111', 'C 240', 'Planeta 4', 'Lacetti', '2104', 'GL 350',
       '642208', 'ML 320', 'Focus', 'T8', 'NX 350h', 'Stonic', 'E 260',
       'LX 500d', 'Fulwin 2', '406', 'GL 63 AMG', 'Next A21R22-30',
       'ID.6', 'E 250', 'Pajero', '2101', '6', 'Continental GT',
       'Outback', 'LX 570', 'Sahin', 'Samand', 'Tourneo Custom',
       'Qashqai', 'Micra', 'Passat', 'Carnival', 'Carens', '33021',
       'IS 250', 'GS 350', 'Sprinter 316', 'Yaris', '69', '105 XF', '320',
       'S 350 d 4Matic', 'Insight', 'CS 75', 'Arrizo 5', 'Sprinter 313',
       'LS 500', 'Leaf', 'E 350 e', '330', '328', 'Accord', '330202-740',
       'Altima', 'S 1000 RR', 'Sentra', 'GX 460', 'Durango', 'Polo',
       '330200', 'X4', 'Duster', 'Sunny', '2110', '3110', 'Eclipse Cross',
       'Gentra', 'Picanto', 'CX-5', 'Rexton', 'L200', 'Avalon', 'Zafira',
       'Auris', 'GLS 350', 'GLC 300', 'Racer', 'Cobalt', 'Q7', 'S 320',
       'RR Velar', 'C 300', 'ES 250', '540', 'Tondar', 'Escape', '31105',
       '208 D', 'Amulet (A15)', 'Rapid', 'ML 350', '740', 'Patrol',
       'S 350', 'Countryman', 'Attrage', 'XC90', 'CR-V', 'B 170',
       'Sprinter 315', 'Slingshot', 'RX 330', 'E 320', '530e', 'Beetle',
       'R 420', 'Venue', '3302-288', 'Aerio', '53', 'S 63 AMG Coupe',
       'CS 15', 'Cayenne S', 'Huracan', 'Laguna', '65115', 'CLS 63 AMG',
       'F2000', 'E 230', 'LX 600', 'Kona', 'Soul', 'Opirus',
       'S 500 4Matic', 'CLA 250', 'FX37', 'K2700', 'Cayenne', 'Vita',
       'NX 300h', 'V 300', 'Teana', 'CX-7', 'M60', 'ML 400', 'Atego 1218',
       'Macan', 'RX 300', 'Ka', 'Corolla Cross', 'E 300', 'Kangoo',
       'CUB50 S', 'Tourneo Connect', 'Model Y', 'Veracruz', 'Genesis',
       'M50', 'Matrix', 'X6', 'MKZ', 'GX 470', 'Sprinter 311', 'K7', 'A8',
       'Touareg', 'Cayenne Turbo', 'Sprinter 312', 'Tiger VH-L', 'LX 450',
       'Atego 814', 'CBR 1000', 'Signum', 'CA5013', '412', 'Creta', '200',
       'FX45', 'R310', 'MP4-12C', 'Meriva', '2109', 'GL 450', 'Juke',
       'Azera', 'Liberty', 'A21R22-03', 'Orlando', '130', 'H6 GT',
       'Tiggo 2 Pro', 'C 350', 'A5', 'GLS 450', 'Galant', 'Outlander',
       'Pride', 'Puma', 'Dogan', 'Avensis', 'Logan', 'Q70', 'Q8',
       'Mustang', 'R15S', '2105', 'NX 200', 'Panther ZT150-8A', '3303',
       'Pajero io', '318', '300 SR', 'G 55 AMG', 'Coolray', 'M-21',
       'Maverick', 'Doblo', 'Mokka', 'Vito 114', 'Tundra', 'Viano', 'iX',
       'Coupe', 'Continental Flying Spur', 'Damas', '24-10', 'GLE 350',
       'Jimmy', 'Forester', 'A4', 'Journey', 'Edge', 'Bentayga', '5511',
       'V 250', 'CX-9', 'K5', 'Drag Star XVS 650', 'X1', 'Panamera Turbo',
       'Dominar 400', 'Navigator', 'Grand Santa Fe', '159', 'Kalina',
       'X6 M', 'ES 300h', 'GLA 250', 'ML 500', 'Mini EV', 'R15 V4',
       'XJ L', 'Wrangler', 'E 300 de', 'XC60', 'Bora', '35C15', 'Excel',
       'Octavia', 'Karoq', 'Niva Travel', 'EQC 400 4MATIC', 'Otoyol',
       'Camaro', 'Cayenne GTS', 'Fluence', '24-02', 'Largus', '12 ЗИМ',
       'Intruder', 'Omega', 'Fora (A21)', 'Jolion', 'Atego 818',
       'Axor 3340', 'Uni-V', '730', 'e-Bora', 'Panamera 4S', 'Insignia',
       'Taycan', 'QX50', 'Nativa', 'Cadenza', '53212', '2757', 'Prius V',
       'C 320', 'S 350 d', '001', 'Navara', '3302-744', 'Koleos', 'M-NV',
       'Q30', 'RS7', 'S 63 AMG', 'Hilux', 'Atego 1229', 'Actros 1844',
       'GL 550', 'Scirocco', '31029', 'R15M', 'GLS 400', 'Vito 112',
       '55111', 'GS5', 'S 560 4Matic', 'Jimny', '848 EVO', '535', '95 XF',
       'H-1', 'Sienna', '965', 'Winner 200', 'Q5', 'A6 allroad', 'M37S',
       'Granta', 'Pilot', 'Clubman', 'Ibiza', 'G 500', 'C41R13', 'H3',
       'Aventador', 'M-1', 'QX55', 'Tiggo 7 Pro', 'Transporter',
       'A7 Sportback', 'Getz', '250 S', 'Tavriya', 'CLA 250 e', 'XL7',
       'Han', 'i10', 'ix55', 'Slavuta', '120', 'ML 300', 'Veloster',
       'Macan S', 'Vario', 'C 32 AMG', 'Ecosport', 'Vaneo', 'ATS',
       'Flying Spur', 'Hover H5', 'Axor 1829', '330e', 'Combo',
       'S 450 4Matic', '3307', 'Monjaro', 'Terracan', 'Rio X-Line',
       'Jetta', 'Mountaineer', 'TGX 18.440', '132', 'E 500',
       'Bestune B30', 'Uni-K', 'S 550', 'Megane Scenic', 'Atego 815',
       '700 CL-X Heritage', 'FH 13', 'Panamera GTS', 'Stinger', 'XF',
       'QX56', 'Scudo', '2114', 'C 280', 'Legacy', 'Bronco Sport',
       'TGX 18.480', 'Taycan Turbo S', 'X3 Pro', 'NX 250', 'Fiesta',
       'GLC 200 4Matic', 'CLS 320', 'Mondeo', 'EX35', 'LX 470', 'Ghibli',
       'C-HR', 'F3', 'Lanos', 'HR-V', 'Scenic', 'FH 16', '750', 'FH 500',
       'Sprinter 411', 'Uni-T', 'Axor 1840', 'Tiggo 5', 'QX60', 'Seltos',
       'Tiba', '250 CL-X', 'CS 95', 'JS8', 'Pajero Pinin', '300C',
       'Emgrand X7', 'Izoa', 'A7', 'Tiggo 8 Pro e+', 'Gladiator',
       'ProCeed', 'Sinotruk', 'F 70', 'Rexton Sports', '650 NK', 'E 400',
       '5301', 'GL 320', 'i40', '308', 'Q50S', 'NX 200t', 'S 600',
       'Axor 1843', 'Multivan', '2102', 'Freelander', 'Model S',
       'GLS 600 4MATIC', 'Amarok', 'Sprinter 524', 'S 280', 'T33',
       'B 180', '760', 'ES 200', 'M45', 'Spark', 'Kodiaq',
       'Pulsar NS 200', 'Ducato', 'A 190', 'CLS 350', 'Versa', 'Rush',
       'GS 300', 'Caliber', '6520', 'Leon', 'Sprinter 515', 'Cherokee',
       'F-Pace R', 'Muravey- 2 01', 'A 170', 'LS 460', 'M5', 'Bolero',
       '240 D', 'Pathfinder', 'Compass', 'GLE 350 Coupe', 'Fiorino',
       'G25', 'Sprinter 509', 'Traverse', 'X3', 'Tugella S', 'Palisade',
       'Solara', '420', 'Turismo', 'Panamera 4', 'Atego 1224', '640',
       'Surf', 'Yaris Cross', 'FJ Cruiser', 'Charger', 'Volt', 'Soren',
       '650', 'FVR 34 Q', 'Besta', 'Verso', 'Aygo', 'Trafic',
       'G 55 Brabus K8', '650 GT', 'GLE 43 AMG Coupe', 'Epica',
       'XF 460 FT', 'LE60', 'Fabia', 'Neon', 'Tiguan', 'R4', 'Swift',
       'CTS', 'Lancer', 'GS 200t', 'Espero', 'Atego 1523', 'Toledo',
       'UX 200', 'Taos', 'GLE 400', '2705-757', 'CS 35', 'Grandis',
       'Airtrek', 'ET5', 'Atego 917', 'GLE 53 AMG Coupe', 'GranTurismo S',
       '428', 'GLC 300 e 4Matic Coupe', 'F-150', 'Vento', 'S 430',
       '65201', 'A 160', '280 E', 'Emgrand', 'Golf', '408', 'F7x',
       'G 230', 'Niro', '5549', 'Genesis Coupe', 'Grand Vitara', 'C-37',
       'C 63 AMG', 'M6', 'F-Type', 'Diavel Carbon', 'Oka', 'Fengshen S30',
       'GLS 63 AMG', 'Kyron', 'MX-5 Miata', 'Stralis', 'CL 63 AMG',
       'Tugella', 'Leganza', '2140', '170 V', 'Xterra', 'Tiggo 2',
       'TGA 18.440', 'MT-15', '2111', 'CS 85', 'Mustang Mach-E', 'Staria',
       'S 400', 'TGA 33.480', 'BJ40', 'Patriot', '595', '1199 Panigale S',
       '31512', 'NPR 66 L', 'Avenger 220', 'JS125-7F', 'X3 M', 'Korando',
       'HC40', 'Discovery Sport', 'E 53 4MATIC+', 'Besturn X80', '3102',
       'Superb', 'GLS 500', 'Atego 1517', 'Mohave', 'GLS 580', 'Cargo',
       'Actros 1846', 'M-20 Pobeda', 'Raeton', 'S90', 'Cooper',
       'Silverado', 'E 63 AMG', 'Tiggo 3', 'Pregio', 'Nubira', 'i20',
       'Boxer', 'Actros 2544', 'F-Type R', 'ZT155-G1', 'Vesta',
       'Tiger VR', 'NPR 75 L', 'LS 600h', 'Fortuner', '2', 'Vida',
       'IS 350', 'FH 12', 'FZ 25', 'Q3', 'IQ', 'Oshan A600', 'Aumark TX',
       'EQE 350', 'GLB 250', 'Vito 113', '11', 'ML 250', 'S 150', 'e:NP1',
       'FZ-S FI Deluxe', 'Axor 1824', 'S 300', '2108',
       'Cayenne GTS Coupe', '735', 'GLC 300 Coupe', 'Next A21R32-30',
       'XV', 'Crossfire', 'Q60', 'GLC 200 4Matic Coupe', '840', '812 D',
       'CS 35 PLUS', 'EuroStar', 'R8', 'Musso', 'Quoris', 'Santana',
       'Sweet (QQ)', 'EQV 300', '24', 'Actros 1848', 'Ecobus', 'Sobol',
       'Eado Plus', 'Kuga', 'Eado', 'Wingle', 'Sprinter 211', '728',
       'Benni', 'Benni E-Star', 'C 300 e', 'X5 M', 'Istiqlal', 'G70',
       'Cayenne Turbo S', 'T77', 'B 200', 'Escalade', 'Sprinter 208',
       'Temsa', 'Vito 116', 'Biznes 330273', '3', 'Niva Bronto',
       'GLA 200', 'Kicks', 'F3000', '33098-837', 'V 220', 'S5', 'Citan',
       'Dargo', 'CLS 500', 'S 55 AMG', 'Crafter', 'Senova D50',
       'Next A65R52', 'Outlander Sport', '2705', 'D51', 'GLC 350', '2103',
       'County', '410 D', '66', 'IONIQ Hybrid', 'TGA 18.480', 'Equus',
       '8S', 'TGA 33350', '307', '150 NK', 'NQR 71 PL', 'UX 250h', 'RS3',
       'X2', 'S7', 'S6', 'CFORCE 520L', 'Renegade', 'Next A22R32',
       '43101', 'Rivale', 'Vitz', 'Forfour', 'Clarus', 'Continental',
       'LS 350', 'Aviator', 'Arteon', 'GL 400', '206', 'C40', 'Prenses',
       '650 MT', '4C', 'Raize', 'HS', 'XE', 'Galloper', 'Atlas Pro',
       'Eldorado', 'SHK', '405', 'GLE 450', 'EQE 350 4Matic',
       'Macan Turbo', 'NX 300', 'NKR 55 L', 'Alphard', 'Travego', '220',
       'GLC 300 e 4Matic', 'S 250', 'Vitara', 'bZ4X', 'SL 63 AMG',
       'D4 125', 'Chorus', 'Passport', 'Alsvin V3', 'H9', '231073',
       'Taycan 4S', 'NAT', 'S-MAX', 'Q50', 'Wingroad', 'HD50', 'Punto',
       'Tahoe', 'Yeti', 'CLA 200', 'C-35', 'Partner', '2715', 'Murano',
       '1125CR', 'Master', '33023-744', '35S10', '551605', '300 NK',
       'Solaris', '3008', 'GT', 'Ranger', 'ZS T', 'Largus Cross',
       'Cerato Koup', 'GS4', 'Sportster Forty Eight', 'Corolla Verso',
       'HS7', '911 Carrera 4S', 'Forland', 'SRX', 'Panamera Turbo S'],
      dtype=object)

In [17]:
encoder = LabelEncoder()
df.model = encoder.fit_transform(df.model)

In [18]:
df["buraxılış ili"].unique()

array([2000, 2023, 2013, 2015, 2022, 2007, 2017, 2009, 2016, 2012, 1999,
       1989, 2011, 1991, 2005, 2006, 1990, 2008, 2003, 1997, 2019, 2021,
       2018, 2014, 2004, 1984, 2001, 2010, 1992, 1996, 1998, 2020, 1995,
       1993, 2002, 1976, 1980, 1979, 1994, 1978, 1985, 1972, 1974, 1988,
       1987, 1986, 1975, 1983, 1965, 1963, 1955, 1966, 1939, 1982, 1967,
       1964, 1938, 1977, 1981, 1970, 1957, 1973, 1956, 1968])

In [19]:
df[df["buraxılış ili"] == 1938]

,avtosalon,qiymet,şəhər,marka,model,buraxılış ili,ban növü,rəng,mühərrik,yürüş,...,yeni,vəziyyəti,yeniləndi,baxışların sayı,extra,etrafli,sahiblər,hansı bazar üçün yığılıb,yerlərin sayı,qəzalı
5067,0,1445000,42,68,11,1938,Kupe,Qara,2.4 L/85 a.g./Benzin,82 000 km,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",15.05.2023,241146,"Dəri salon, Ksenon lampalar",Ideal veziyyetdedir. Bos-bekar adamlar narahat...,NaN,NaN,NaN,NaN

In [20]:
df["ban növü"].unique()

array(['Hetçbek', 'Sedan', 'Offroader / SUV', 'Liftbek', 'Universal',
       'Kupe', 'Yük maşını', 'Furqon', 'Minivan', 'Dartqı',
       'Mikroavtobus', 'Motosiklet', 'Pikap', 'Van', 'Avtobus',
       'Kvadrosikl', 'Rodster', 'Moped', 'Kabriolet'], dtype=object)

In [21]:
df.rəng.unique()

array(['Göy', 'Mavi', 'Qara', 'Gümüşü', 'Tünd qırmızı', 'Boz', 'Ağ',
       'Bej', 'Yaş Asfalt', 'Yaşıl', 'Qızılı', 'Narıncı', 'Sarı',
       'Qırmızı', 'Qəhvəyi', 'Çəhrayı', 'Bənövşəyi'], dtype=object)

In [22]:
encoder = LabelEncoder()
df.rəng = encoder.fit_transform(df.rəng)

In [23]:
df.mühərrik.value_counts()

mühərrik
2.0 L/184 a.g./Dizel      503
1.6 L/75 a.g./Benzin      321
2.0 L/245 a.g./Benzin     265
1.5 L/76 a.g./Hibrid      180
1.4 L/90 a.g./Benzin      169
                         ...
3.0 L/170 a.g./Dizel        1
3.5 L/250 a.g./Benzin       1
0.0 L/268 a.g./Elektro      1
1.2 L/75 a.g./Dizel         1
0.1 L/75 a.g./Benzin        1
Name: count, Length: 1307, dtype: int64

In [24]:
df[["litr", "at_gücü", "yanacaq"]] = df.mühərrik.str.split("/", expand=True)
df.drop(columns = "mühərrik", inplace=True)

df.insert(8, "litr", df.pop("litr"))
df.insert(9, "at_gücü", df.pop("at_gücü"))
df.insert(10, "yanacaq", df.pop("yanacaq"))

In [25]:
df.litr

0       1.6 L
1       1.8 L
2       2.0 L
3       1.5 L
4       2.0 L
        ...
9995    2.0 L
9996    3.0 L
9997    1.6 L
9998    2.0 L
9999    1.6 L
Name: litr, Length: 10000, dtype: object

In [26]:
df.litr = df.litr.str.strip(" L").astype(float)
df.at_gücü = df.at_gücü.str.strip(" a.g.").astype(int)

In [27]:
df.yanacaq.unique()

array(['Benzin', 'Hibrid', 'Dizel', 'Elektro', 'Plug-in Hibrid', 'Qaz'],
      dtype=object)

In [28]:
encoder = LabelEncoder()
df.yanacaq = encoder.fit_transform(df.yanacaq)

In [29]:
df.yürüş.unique()

array(['370 000 km', '0 km', '168 636 km', ..., '61 130 km', '299 785 km',
       '181 500 km'], dtype=object)

In [30]:
df.yürüş = df.yürüş.str.strip(" km").str.replace(" ", "").astype(int)

In [31]:
print(df["sürətlər qutusu"].unique())
df["sürətlər qutusu"] = encoder.fit_transform(df["sürətlər qutusu"])

['Mexaniki' 'Avtomat' 'Variator' 'Robotlaşdırılmış']

In [32]:
print(df["ötürücü"].unique())
df["ötürücü"] = encoder.fit_transform(df["ötürücü"])

['Ön' 'Arxa' 'Tam']

In [33]:
print(df.yeni.unique())
df.yeni = df.yeni.replace({"Xeyr": 0, "Bəli":1}).astype(int)

['Xeyr' 'Bəli']

In [34]:
print(df.vəziyyəti.unique())

df[["vuruq", "rənglənib"]] = df.vəziyyəti.str.split(", ", expand=True)
df.drop(columns="vəziyyəti", inplace=True)

['Vuruğu yoxdur, rənglənib' 'Vuruğu yoxdur, rənglənməyib'
 'Vuruğu var, rənglənib' 'Vuruğu var, rənglənməyib' nan]

In [35]:
print(df.vuruq.unique())
print(df.rənglənib.unique())

df.vuruq = df.vuruq.replace({"Vuruğu yoxdur": 0, "Vuruğu var": 1, np.nan: 0}).astype(int)
df.rənglənib = df.rənglənib.replace({"rənglənib": 1, "rənglənməyib": 0, np.nan: 0}).astype(int)

df.insert(15, "vuruq", df.pop("vuruq"))
df.insert(16, "rənglənib", df.pop("rənglənib"))

['Vuruğu yoxdur' 'Vuruğu var' nan]
['rənglənib' 'rənglənməyib' nan]

In [36]:
print(df.yeniləndi.unique())
df.yeniləndi = pd.to_datetime(df.yeniləndi, dayfirst=True)

[' 28.05.2023' ' 25.05.2023' ' 27.05.2023' ' 26.05.2023' ' 17.05.2023'
 ' 18.05.2023' ' 10.05.2023' ' 19.05.2023' ' 24.05.2023' ' 22.05.2023'
 ' 20.05.2023' ' 23.05.2023' ' 21.05.2023' ' 02.05.2023' ' 16.05.2023'
 ' 05.05.2023' ' 04.05.2023' ' 29.04.2023' ' 15.05.2023' ' 03.05.2023'
 ' 12.05.2023' ' 01.05.2023' ' 14.05.2023' ' 06.05.2023' ' 08.05.2023'
 ' 09.05.2023' ' 13.05.2023' ' 30.04.2023' ' 11.05.2023' ' 07.05.2023']

In [37]:
df["baxışların sayı"].unique()

array([  267, 12410,   148, ...,  3299, 17368,  1182])

In [38]:
df.extra

0       Yüngül lehimli disklər, ABS, Kondisioner, Dəri...
1       Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...
2       Yüngül lehimli disklər, ABS, Lyuk, Yağış senso...
3       Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...
4       Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...
                              ...
9995    Yüngül lehimli disklər, ABS, Lyuk, Yağış senso...
9996    Yüngül lehimli disklər, ABS, Lyuk, Yağış senso...
9997    Yüngül lehimli disklər, ABS, Mərkəzi qapanma, ...
9998    Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...
9999                               Yüngül lehimli disklər
Name: extra, Length: 10000, dtype: object

In [39]:
# adding extra features to a single set
print(df.extra.unique())

df.extra = df.extra.fillna(df.extra.mode().iloc[0])
splitted = df.extra.str.split(", ")

extras = set()

for cell in splitted:
    extras.update(cell)

['Yüngül lehimli disklər, ABS, Kondisioner, Dəri salon, Ksenon lampalar, Yan pərdələr'
 'Yüngül lehimli disklər, ABS, Yağış sensoru, Mərkəzi qapanma, Park radarı, Kondisioner, Oturacaqların isidilməsi, Ksenon lampalar, Arxa görüntü kamerası, Yan pərdələr, Oturacaqların ventilyasiyası'
 'Yüngül lehimli disklər, ABS, Lyuk, Yağış sensoru, Mərkəzi qapanma, Park radarı, Kondisioner, Oturacaqların isidilməsi, Dəri salon, Ksenon lampalar, Arxa görüntü kamerası, Yan pərdələr, Oturacaqların ventilyasiyası'
 ...
 'ABS, Yağış sensoru, Kondisioner, Oturacaqların isidilməsi, Dəri salon'
 'Yüngül lehimli disklər, ABS, Mərkəzi qapanma, Park radarı, Kondisioner, Dəri salon, Arxa görüntü kamerası, Yan pərdələr, Oturacaqların ventilyasiyası'
 'Yüngül lehimli disklər, ABS, Lyuk, Mərkəzi qapanma, Kondisioner, Dəri salon, Ksenon lampalar, Yan pərdələr, Oturacaqların ventilyasiyası']

In [40]:
extras

{'ABS',
 'Arxa görüntü kamerası',
 'Dəri salon',
 'Kondisioner',
 'Ksenon lampalar',
 'Lyuk',
 'Mərkəzi qapanma',
 'Oturacaqların isidilməsi',
 'Oturacaqların ventilyasiyası',
 'Park radarı',
 'Yan pərdələr',
 'Yağış sensoru',
 'Yüngül lehimli disklər'}

In [41]:
# creating new binary columns based on the values from extra column.
extras = list(extras)
df[extras] = 0

for i in df[extras].columns:
    df[i] = (df.extra.str.contains(i))

In [42]:
df.extra[0]

'Yüngül lehimli disklər, ABS, Kondisioner, Dəri salon, Ksenon lampalar, Yan pərdələr'

In [43]:
df[extras]

,Arxa görüntü kamerası,Yağış sensoru,Park radarı,Oturacaqların isidilməsi,Dəri salon,ABS,Mərkəzi qapanma,Ksenon lampalar,Lyuk,Kondisioner,Yan pərdələr,Oturacaqların ventilyasiyası,Yüngül lehimli disklər
0,False,False,False,False,True,True,False,True,False,True,True,False,True
1,True,True,True,True,False,True,True,True,False,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,False,False,True,True,True,False,True,True,False,True
4,True,True,True,True,True,True,True,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,True,False,True,True,True,True,True,True,True,True,False,True
9996,True,True,True,True,True,True,True,True,True,True,True,True,True
9997,True,False,True,False,False,True,True,False,False,True,False,False,True
9998,True,True,True,False,True,True,True,True,False,True,False,True,True
9999,False,False,False,False,False,False,False,False,False,False,False,False,True

In [44]:
df.drop(columns = "extra", inplace=True)
df.columns = df.columns.str.lower()

In [45]:
df.etrafli = df.etrafli.astype('string')

In [46]:
print(df.sahiblər.value_counts(dropna=False))

# if a car has some kilometers then it must have at least 1 owner, if hasn't then the car is new.
df.loc[(df.yürüş!=0) & (df.sahiblər.isna()), "sahiblər"] = 1
df.loc[(df.yürüş==0) & (df.sahiblər.isna()), "sahiblər"] = 0

df.sahiblər = df.sahiblər.replace({"4 və daha çox":4}).astype(int)

sahiblər
NaN              3807
1                2850
2                2282
0                 607
3                 373
4 və daha çox      81
Name: count, dtype: int64

# Handling Missing Values

KNN Imputation

In [47]:
df["hansı bazar üçün yığılıb"].value_counts(dropna=False).head()

hansı bazar üçün yığılıb
NaN            3298
Avropa         2087
Rəsmi diler    1447
Amerika        1311
Koreya          697
Name: count, dtype: int64

In [48]:
df_imputed = df.copy()
df_imputed["hansı bazar üçün yığılıb"] = df_imputed["hansı bazar üçün yığılıb"].astype('category').cat.codes

imputer = KNNImputer(n_neighbors=2)
df_imputed[["hansı bazar üçün yığılıb"]] = imputer.fit_transform(df_imputed[["hansı bazar üçün yığılıb"]])

df["hansı bazar üçün yığılıb"] = df_imputed["hansı bazar üçün yığılıb"].astype(int)

Filling Nan values for seats based on the type of cars

In [49]:
df["yerlərin sayı"].value_counts(dropna=False)

yerlərin sayı
5      4372
NaN    3168
7      1194
4       831
3       187
2       115
8+       74
6        40
1        19
Name: count, dtype: int64

In [50]:
seats = {
    'Hetçbek': 2,
    'Sedan': 5,
    'Offroader / SUV': 4,
    'Liftbek': 5,
    'Universal': 5,
    'Kupe': 4,
    'Yük maşını': 3,
    'Furqon': 3,
    'Minivan': 8,
    'Dartqı': 2,
    'Mikroavtobus': 8,
    'Motosiklet': 2,
    'Pikap': 5,
    'Van': 8,
    'Avtobus': 8,
    'Kvadrosikl': 1,
    'Rodster': 2,
    'Moped': 1,
    'Kabriolet': 4
}

In [51]:
for k, i in seats.items():
    df.loc[(df["ban növü"] == k) & (df["yerlərin sayı"].isna()), "yerlərin sayı"] = i

df["yerlərin sayı"] = df["yerlərin sayı"].replace("8+", 8).astype(int)

In [52]:
encoder = LabelEncoder()
df["ban növü"] = encoder.fit_transform(df["ban növü"])

In [53]:
print(df["qəzalı"].value_counts(dropna=False))
df["qəzalı"] = df["qəzalı"].fillna(0).replace("Bəli", 1).astype(int)

qəzalı
NaN     9968
Bəli      32
Name: count, dtype: int64

In [54]:
# if car has a damage or painted then 'qəzalı' column must be True
df.loc[(df.vuruq == 1) & (df.rənglənib == 1) & (df["qəzalı"]==0), "qəzalı"] = 1
df["qəzalı"].value_counts(dropna=False)

qəzalı
0    9899
1     101
Name: count, dtype: int64

# Model Building

In [55]:
df.head()

,avtosalon,qiymet,şəhər,marka,model,buraxılış ili,ban növü,rəng,litr,at_gücü,...,oturacaqların isidilməsi,dəri salon,abs,mərkəzi qapanma,ksenon lampalar,lyuk,kondisioner,yan pərdələr,oturacaqların ventilyasiyası,yüngül lehimli disklər
0,0,13500,6,78,828,2000,3,4,1.60,101,...,False,True,True,False,True,False,True,True,False,True
1,1,39950,6,99,278,2023,15,6,1.80,178,...,True,False,True,True,True,False,True,True,True,True
2,0,33200,6,41,726,2013,12,8,2.00,184,...,True,True,True,True,True,True,True,True,True,True
3,0,17000,6,26,384,2015,15,4,1.50,181,...,False,False,True,True,True,False,True,True,False,True
4,0,61200,6,99,672,2022,12,8,2.00,173,...,True,True,True,True,True,False,True,False,False,True

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   avtosalon                     10000 non-null  int64
 1   qiymet                        10000 non-null  int64
 2   şəhər                         10000 non-null  int64
 3   marka                         10000 non-null  int64
 4   model                         10000 non-null  int64
 5   buraxılış ili                 10000 non-null  int64
 6   ban növü                      10000 non-null  int64
 7   rəng                          10000 non-null  int64
 8   litr                          10000 non-null  float64
 9   at_gücü                       10000 non-null  int64
 10  yanacaq                       10000 non-null  int64
 11  yürüş                         10000 non-null  int64
 12  sürətlər qutusu               10000 non-null  int64
 13  ötürücü                       10000 non-null  int64
 14  yeni                          10000 non-null  int64
 15  vuruq                         10000 non-null  int64
 16  rənglənib                     10000 non-null  int64
 17  yeniləndi                     10000 non-null  datetime64[ns]
 18  baxışların sayı               10000 non-null  int64
 19  etrafli                       9718 non-null   string
 20  sahiblər                      10000 non-null  int64
 21  hansı bazar üçün yığılıb      10000 non-null  int64
 22  yerlərin sayı                 10000 non-null  int64
 23  qəzalı                        10000 non-null  int64
 24  arxa görüntü kamerası         10000 non-null  bool
 25  yağış sensoru                 10000 non-null  bool
 26  park radarı                   10000 non-null  bool
 27  oturacaqların isidilməsi      10000 non-null  bool
 28  dəri salon                    10000 non-null  bool
 29  abs                           10000 non-null  bool
 30  mərkəzi qapanma               10000 non-null  bool
 31  ksenon lampalar               10000 non-null  bool
 32  lyuk                          10000 non-null  bool
 33  kondisioner                   10000 non-null  bool
 34  yan pərdələr                  10000 non-null  bool
 35  oturacaqların ventilyasiyası  10000 non-null  bool
 36  yüngül lehimli disklər        10000 non-null  bool
dtypes: bool(13), datetime64[ns](1), float64(1), int64(21), string(1)
memory usage: 2.0 MB

In [57]:
# We don't need these columns for prediction
df.drop(columns=["etrafli", "yeniləndi"], inplace=True)

In [58]:
x = df.drop(columns = "qiymet")
y= df.qiymet

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Lazzy Regressor Results

In [59]:
reg = LazyRegressor(verbose=0, ignore_warnings=False, custom_metric=None)
models, predictions = reg.fit(x_train, x_test, y_train, y_test)

print(models)

 98%|█████████▊| 41/42 [01:06<00:01,  1.13s/it]

XGBRegressor model failed to execute
'super' object has no attribute '__sklearn_tags__'
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001339 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1337
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 21
[LightGBM] [Info] Start training from score 36220.903000

100%|██████████| 42/42 [01:06<00:00,  1.59s/it]

                               Adjusted R-Squared  R-Squared       RMSE  \
Model
HistGradientBoostingRegressor                0.93       0.94   12125.39
LGBMRegressor                                0.92       0.92   13367.22
ExtraTreesRegressor                          0.90       0.90   14998.93
RandomForestRegressor                        0.87       0.87   17282.19
KNeighborsRegressor                          0.82       0.82   20329.13
BaggingRegressor                             0.78       0.78   22229.83
PoissonRegressor                             0.75       0.75   23850.42
GradientBoostingRegressor                    0.69       0.70   26328.96
SGDRegressor                                 0.59       0.59   30483.58
LassoLarsIC                                  0.57       0.58   30887.92
LassoCV                                      0.57       0.58   30899.50
BayesianRidge                                0.57       0.58   30905.59
LassoLarsCV                                  0.57       0.58   30906.82
LarsCV                                       0.57       0.58   30906.82
RidgeCV                                      0.57       0.58   30907.76
LassoLars                                    0.57       0.58   30909.46
Lasso                                        0.57       0.58   30909.46
Ridge                                        0.57       0.58   30909.59
LinearRegression                             0.57       0.58   30909.80
TransformedTargetRegressor                   0.57       0.58   30909.80
Lars                                         0.57       0.58   30909.80
OrthogonalMatchingPursuitCV                  0.55       0.55   31882.00
DecisionTreeRegressor                        0.54       0.55   32113.16
ElasticNet                                   0.54       0.54   32259.77
OrthogonalMatchingPursuit                    0.53       0.54   32316.81
ExtraTreeRegressor                           0.51       0.51   33286.65
HuberRegressor                               0.50       0.51   33603.71
TweedieRegressor                             0.49       0.50   33662.29
GammaRegressor                               0.49       0.50   33827.79
PassiveAggressiveRegressor                   0.49       0.49   33966.07
MLPRegressor                                 0.41       0.42   36280.13
RANSACRegressor                              0.34       0.35   38623.43
AdaBoostRegressor                            0.08       0.09   45549.40
ElasticNetCV                                 0.06       0.08   45803.97
KernelRidge                                 -0.01       0.01   47638.16
DummyRegressor                              -0.02      -0.00   47791.01
NuSVR                                       -0.07      -0.05   48912.17
SVR                                         -0.12      -0.10   50133.15
QuantileRegressor                           -0.13      -0.11   50262.92
LinearSVR                                   -0.36      -0.34   55336.24
GaussianProcessRegressor                  -687.37    -675.66 1242786.59

                               Time Taken
Model
HistGradientBoostingRegressor        0.50
LGBMRegressor                        0.23
ExtraTreesRegressor                  8.22
RandomForestRegressor                5.32
KNeighborsRegressor                  0.20
BaggingRegressor                     0.70
PoissonRegressor                     0.04
GradientBoostingRegressor            1.37
SGDRegressor                         0.05
LassoLarsIC                          0.04
LassoCV                              0.14
BayesianRidge                        0.05
LassoLarsCV                          0.07
LarsCV                               0.07
RidgeCV                              0.04
LassoLars                            0.03
Lasso                                0.03
Ridge                                0.02
LinearRegression                     0.03
TransformedTargetRegressor           0.02
Lars                                 0.03
OrthogonalMatchingPursuitCV          0.04
DecisionTreeRegressor                0.18
ElasticNet                           0.02
OrthogonalMatchingPursuit            0.02
ExtraTreeRegressor                   0.07
HuberRegressor                       0.13
TweedieRegressor                     0.04
GammaRegressor                       0.05
PassiveAggressiveRegressor           0.10
MLPRegressor                         6.23
RANSACRegressor                      0.20
AdaBoostRegressor                    0.79
ElasticNetCV                         0.12
KernelRidge                          6.22
DummyRegressor                       0.02
NuSVR                                4.50
SVR                                  5.55
QuantileRegressor                    2.33
LinearSVR                            0.04
GaussianProcessRegressor            22.53

In [60]:
def metrics(y_pred, y_test):
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    print(f"Mean Squered Error: {mse}\nMean Absolute Error: {mae}\nR-squared: {r2}")

In [61]:
lr = LinearRegression()
lr.fit(x_train, y_train)

y_pred = lr.predict(x_test)
metrics(y_pred, y_test)

Mean Squered Error: 944987401.310478
Mean Absolute Error: 16819.815148095517
R-squared: 0.5859961155801163

# Neural Network

In [62]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation="relu", input_shape = (34, )),
    tf.keras.layers.Dense(512, activation="relu", kernel_regularizer="l2"),
    tf.keras.layers.Dense(512, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(512, activation="relu"),
    tf.keras.layers.Dense(256, activation="relu", kernel_regularizer="l2"),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dense(1)
    ])

model.compile(optimizer="adam", loss="mean_absolute_error")

In [63]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=20)

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 28094.9961 - val_loss: 21417.8340
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 20217.8418 - val_loss: 19339.2832
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 19112.4062 - val_loss: 18386.2461
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 18324.3145 - val_loss: 18779.0605
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 17064.8711 - val_loss: 14515.5107
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 15431.4111 - val_loss: 12983.2207
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 14676.8711 - val_loss: 14093.3818
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 13931.5146 - val_loss: 12760.4873
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13086.1445 - val_loss: 13032.6240
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13596.8633 - val_loss: 12367.0078
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 13483.6904 - val_loss: 12821.4453
Epoch 12/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13229.1484 - val_loss: 12894.2256
Epoch 13/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12826.5518 - val_loss: 12240.8145
Epoch 14/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12919.9824 - val_loss: 13585.7363
Epoch 15/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13822.4150 - val_loss: 13169.6084
Epoch 16/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12384.6826 - val_loss: 13487.8281
Epoch 17/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12192.6338 - val_loss: 12859.7021
Epoch 18/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 12794.4209 - val_loss: 12674.2910
Epoch 19/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 12921.3223 - val_loss: 11848.7578
Epoch 20/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 12436.1982 - val_loss: 12714.1953

In [64]:
y_pred = model.predict(x_test)
metrics(y_pred, y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Mean Squered Error: 617093760.0
Mean Absolute Error: 12706.5341796875
R-squared: 0.7296479940414429